#!/bin/bash
#$$ -N ${study}_${sub}
#$$ -q long.qc
#$$ -o $out_dir/logs
#$$ -e $out_dir/logs

singularity run --cleanenv -B $packages_dir $singularity_image \
    $raw_dir $out_dir \
    participant \
    --participant-label $sub_id \
    --ignore slicetiming \
    --fs-license-file $FS_license \
    --fs-no-reconall \
    -w $out_dir/${study}_${sub}_work \
    --mem-mb 13000 \
    --low-mem \
    --resource-monitor \
    --nthreads 4 \
    -vvv

