---
title: "ProjectName"
author: "Your Name"
date: "11 Jul 2017"
output: html_document
---

## Install R Markdown 
```{r Install R Markdown}
# install.packages("rmarkdown")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install required packages 
```{r install required packages}
# install.packages("ggplot2")
# install.packages("cowplot")
```

## Load libraries 
```{r Load required libraries, message=FALSE}
library(ggplot2)
library(cowplot)
```

## Main variables
```{r Main variables}
N=50 # Number of subjects
PATH_HOME = "/home/simon"
PATH_PROJ = file.path(PATH_HOME, "Dropbox", "Data", "ProjectName")  # Project path
PATH_DATA = file.path(PATH_PROJ, 'data') # path where time series data is stored
```

## Figure 1
```{r Analysis xy, fig.height=3, fig.width=3}
N=100
d=data.frame(value=c(rnorm(N/2,1),rnorm(N/2,1)+1.5), group=as.factor(c(rep(1,N/2), rep(2,N/2))))

ggplot(d, aes(x=group, y=value, fill=NULL, color=group)) + geom_boxplot(width=0.4) +
   geom_point(shape=1, color="gray70", size=3, position = position_jitter(width = 0.2, height = 0.001))

```

